// front-end-angular/src/app/components/auth/signup/signup.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  WritableSignal,
  signal,
} from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  FormsModule,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { matchPasswords } from './match-paswords-validaor';
import { TrimInputDirective } from '../trim-input.directive';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../services/authService.service';
import { take } from 'rxjs';
import { ErrorResponse } from '../../../types/error-response';
import { faEnvelope, faLock, faUser } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    TrimInputDirective,
    FontAwesomeModule,
  ],
  templateUrl: './signup.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: '../auth.css',
})
export class SignupComponent {
  signupForm: FormGroup;
  errorMessage: WritableSignal<string | null> = signal(null);
  pswIcon = faLock;
  userIcon = faUser;
  emailIcon = faEnvelope;

  constructor(
    fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.signupForm = fb.group(
      {
        username: ['', [Validators.required, Validators.minLength(3)]],
        email: [
          '',
          [
            Validators.required,
            Validators.pattern(/^[^\s@]+@[^\s@]+\.[^\s@]+$/),
          ],
        ],
        password: [
          '',
          [
            Validators.required,
            Validators.pattern(
              /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/
            ),
          ],
        ],
        confirmPassword: ['', Validators.required],
      },
      {
        validators: matchPasswords,
      }
    );
  }

  onSubmit() {
    if (this.signupForm.valid) {
      this.errorMessage.set(null);
      this.authService
        .signUpUser(
          this.signupForm.value.username,
          this.signupForm.value.email,
          this.signupForm.value.password
        )
        .pipe(take(1))
        .subscribe({
          next: () => {
            this.router.navigate(['/']);
          },
          error: (response) => {
            this.errorMessage.set((response.error as ErrorResponse).error);
          },
        });
    }
  }

  // Check if the form control is invalid and if it has been both touched and dirty.
  // If both conditions are met, return true; otherwise, return false.
  public isInvalidInput(inputName: string): boolean {
    return !!(
      this.signupForm.get(inputName)?.invalid &&
      this.isDirtyAndTouched(inputName)
    );
  }

  // Check if the form control is both dirty and touched.
  // If both conditions are met, return true; otherwise, return false.
  // A control is marked touched once the user has triggered a blur event on it.
  // A control is dirty if the user has changed the value in the UI.
  public isDirtyAndTouched(inputName: string): boolean {
    return !!(
      this.signupForm.get(inputName)?.dirty &&
      this.signupForm.get(inputName)?.touched
    );
  }
}

<div
  class="flex flex-col items-center justify-center min-h-screen bg-gradient-to-r from-blue-500 to-blue-900 overflow-scroll"
>
  <img
    src="/logo-white-notitle.png"
    alt="Logo"
    class="w-24 h-24 mb-4 animate"
  />
  <form
    [formGroup]="signupForm"
    (ngSubmit)="onSubmit()"
    class="bg-white px-6 pb-6 pt-4 mb-3 rounded-lg shadow-lg w-full max-w-sm animate"
  >
    <h2 class="text-xl font-bold text-center text-gray-700 mb-4">
      Create Your Account
    </h2>
    <div class="mb-5">
      <label class="block text-gray-700 text-xs font-bold mb-1" for="username"
        >Username</label
      >
      <div class="relative">
        <fa-icon
          [icon]="userIcon"
          class="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400"
        ></fa-icon>
        <input
          type="text"
          trimInput
          id="username"
          formControlName="username"
          class="w-full pl-8 pr-2 py-1.5 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500"
          placeholder="Enter your username"
        />
      </div>
      @if(isInvalidInput('username')){ @if
      (signupForm.get('username')?.hasError('required')) {
      <span class="text-red-500 text-xs mt-1">username is required</span>
      } @if (signupForm.get('username')?.errors?.['minlength']) {
      <span class="text-red-500 text-xs mt-1">
        username must be at least 3 characters long
      </span>
      } }
    </div>

    <div class="mb-5">
      <label class="block text-gray-700 text-xs font-bold mb-1" for="email"
        >email</label
      >
      <div class="relative">
        <fa-icon
          [icon]="emailIcon"
          class="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400"
        ></fa-icon>
        <input
          type="text"
          trimInput
          id="email"
          formControlName="email"
          class="w-full pl-8 pr-2 py-1.5 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500"
          placeholder="Enter your email"
        />
      </div>
      @if(isInvalidInput('email')){ @if
      (signupForm.get('email')?.hasError('required')) {
      <span class="text-red-500 text-xs mt-1">email is required</span>
      } @if (signupForm.get('email')?.errors?.['pattern']) {
      <span class="text-red-500 text-xs mt-1"> invalid email </span>
      } }
    </div>

    <div class="mb-5">
      <label class="block text-gray-700 text-xs font-bold mb-1" for="password"
        >Password</label
      >
      <div class="relative">
        <fa-icon
          [icon]="pswIcon"
          class="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400"
        ></fa-icon>
        <input
          type="password"
          id="password"
          formControlName="password"
          class="w-full pl-8 pr-2 py-1.5 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500"
          placeholder="Enter your password"
        />
      </div>
      @if(isInvalidInput('password')){ @if
      (signupForm.get('password')?.hasError('required')) {
      <span class="text-red-500 text-xs mt-1">password is required</span>
      } @if (signupForm.get('password')?.errors?.['pattern']) {
      <span class="text-red-500 text-xs mt-1"> invalid password </span>
      } }
    </div>
    <div class="mb-5">
      <label
        class="block text-gray-700 text-xs font-bold mb-1"
        for="confirmPassword"
        >confirmPassword</label
      >
      <div class="relative">
        <fa-icon
          [icon]="pswIcon"
          class="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400"
        ></fa-icon>
        <input
          type="password"
          id="confirmPassword"
          formControlName="confirmPassword"
          class="w-full pl-8 pr-2 py-1.5 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500"
          placeholder="Confirm your password"
        />
      </div>
      @if(isInvalidInput('confirmPassword')){ @if
      (signupForm.get('confirmPassword')?.hasError('required')) {
      <span class="text-red-500 text-xs mt-1"
        >please confirm your password</span
      >
      }} @if (isDirtyAndTouched('confirmPassword') &&
      signupForm.hasError('passwordmatcherror')) {
      <span class="text-red-500 text-xs mt-1"> passwords don't match </span>
      }
    </div>

    <button
      type="submit"
      class="w-full bg-blue-700 text-white py-1.5 px-3 rounded-md shadow-md hover:bg-blue-600 hover:scale-105 transition-transform focus:outline-none focus:ring-2 focus:ring-blue-200"
      [disabled]="signupForm.invalid"
    >
      Sign Up
    </button>
    <div class="mt-4 text-center">
      <span class="text-gray-600 text-xs"
        >Already have an account?
        <a routerLink="/login" class="text-blue-500 hover:underline"
          >Login</a
        ></span
      >
    </div>
    <!-- ? Errors from server  -->
    @if(errorMessage()){

    <div class="mt-4 text-center text-red-500">
      {{ errorMessage() }}
    </div>
    }
  </form>
</div>

// front-end/src/components/auth/SignUp.tsx
// src/components/auth/SignUp.tsx
import React, { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useAuthService } from "../../services/authService";
import { FaUser, FaEnvelope, FaLock } from "react-icons/fa";

const SignUp: React.FC = () => {
	const [username, setUsername] = useState<string>("");
	const [email, setEmail] = useState<string>("");
	const [password, setPassword] = useState<string>("");
	const [confirmPassword, setConfirmPassword] = useState<string>("");
	const [errors, setErrors] = useState<{ [key: string]: string }>({});

	const navigate = useNavigate();
	const { signUpUser } = useAuthService();

	const validateEmail = (email: string) => {
		const re = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
		return re.test(email);
	};

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		const newErrors: { [key: string]: string } = {};

		if (username.trim().length === 0) {
			newErrors.username = "Username is required";
		}
		if (!validateEmail(email)) {
			newErrors.email = "Invalid email address";
		}
		if (password.length < 6) {
			newErrors.password = "Password must be at least 6 characters long";
		}
		if (password !== confirmPassword) {
			newErrors.confirmPassword = "Passwords do not match";
		}

		if (Object.keys(newErrors).length > 0) {
			setErrors(newErrors);
			return;
		}

		setErrors({});

		try {
			await signUpUser(username, email, password);
			navigate("/login");
		} catch (error) {
			console.error(error);
			alert("Sign up failed");
		}
	};

	return (
		<div className="flex flex-col items-center justify-center min-h-screen h-fit bg-gradient-to-r from-cyan-600 to-blue-900">
			<img
				src="/logo-white-notitle.png"
				alt="Logo"
				className="w-24 h-24 mb-4 animate-bounce"
			/>
			<form
				onSubmit={handleSubmit}
				className="bg-white px-6 pb-4 pt-4 rounded-lg shadow-lg w-full max-w-sm"
			>
				<h2 className="text-xl font-bold text-center text-gray-700 mb-4">
					Create Your Account
				</h2>
				<div className="mb-3">
					<label
						className="block text-gray-700 text-xs font-bold mb-1"
						htmlFor="username"
					>
						Username
					</label>
					<div className="relative">
						<FaUser className="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400" />
						<input
							type="text"
							id="username"
							value={username}
							onChange={(e) => setUsername(e.target.value)}
							className={`w-full pl-8 pr-2 py-1.5 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500 ${
								errors.username ? "border-red-500" : "border-gray-300"
							}`}
							placeholder="Enter your username"
						/>
					</div>
					{errors.username && (
						<p className="text-red-500 text-xs mt-1">{errors.username}</p>
					)}
				</div>
				<div className="mb-3">
					<label
						className="block text-gray-700 text-xs font-bold mb-1"
						htmlFor="email"
					>
						Email
					</label>
					<div className="relative">
						<FaEnvelope className="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400" />
						<input
							type="email"
							id="email"
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							className={`w-full pl-8 pr-2 py-1.5 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500 ${
								errors.email ? "border-red-500" : "border-gray-300"
							}`}
							placeholder="Enter your email"
						/>
					</div>
					{errors.email && (
						<p className="text-red-500 text-xs mt-1">{errors.email}</p>
					)}
				</div>
				<div className="mb-3">
					<label
						className="block text-gray-700 text-xs font-bold mb-1"
						htmlFor="password"
					>
						Password
					</label>
					<div className="relative">
						<FaLock className="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400" />
						<input
							type="password"
							id="password"
							value={password}
							onChange={(e) => setPassword(e.target.value)}
							className={`w-full pl-8 pr-2 py-1.5 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500 ${
								errors.password ? "border-red-500" : "border-gray-300"
							}`}
							placeholder="Enter your password"
						/>
					</div>
					{errors.password && (
						<p className="text-red-500 text-xs mt-1">{errors.password}</p>
					)}
				</div>
				<div className="mb-5">
					<label
						className="block text-gray-700 text-xs font-bold mb-1"
						htmlFor="confirm-password"
					>
						Confirm Password
					</label>
					<div className="relative">
						<FaLock className="absolute top-1/2 transform -translate-y-1/2 left-2 text-gray-400" />
						<input
							type="password"
							id="confirm-password"
							value={confirmPassword}
							onChange={(e) => setConfirmPassword(e.target.value)}
							className={`w-full pl-8 pr-2 py-1.5 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-500 ${
								errors.confirmPassword ? "border-red-500" : "border-gray-300"
							}`}
							placeholder="Confirm your password"
						/>
					</div>
					{errors.confirmPassword && (
						<p className="text-red-500 text-xs mt-1">
							{errors.confirmPassword}
						</p>
					)}
				</div>
				<button
					type="submit"
					className="w-full bg-blue-700 text-white py-1.5 px-3 rounded-md shadow-md hover:bg-blue-600 hover:scale-105 transition-transform focus:outline-none focus:ring-2 focus:ring-blue-200"
				>
					Sign Up
				</button>
				<div className="mt-4 text-center">
					<span className="text-gray-600 text-xs">
						Already have an account?{" "}
						<Link
							to="/login"
							className="text-blue-500 hover:underline"
						>
							Login
						</Link>
					</span>
				</div>
			</form>
		</div>
	);
};

export default SignUp;
