// front-end-angular/src/app/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/authService.service';
import { take } from 'rxjs';

@Component({
  selector: 'app-navigation',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css'],
})
export class NavigationComponent {
  constructor(public authService: AuthService, private router: Router) {}

  handleLogout() {
    this.authService
      .logoutUser()
      .pipe(take(1))
      .subscribe({
        next: () => {
          localStorage.removeItem('authToken');
          sessionStorage.removeItem('authToken');
          this.router.navigate(['/login']);
        },
      });
  }
}

<nav class="bg-white p-2 shadow">
  <ul class="flex items-center justify-start space-x-6">
    <li class="self-start">
      <a routerLink="/">
        <img src="/logo-white-notitle.png" alt="Logo" class="h-10 w-10" />
      </a>
    </li>

    <!-- ? Conditional rendering  -->

    @if (authService.isLoggedIn$ | async) {
    <li>
      <a
        routerLink="/notes"
        routerLinkActive="is-active"
        [routerLinkActiveOptions]="{ exact: true }"
        >Notes</a
      >
    </li>
    <li>
      <a
        routerLink="/create-note"
        routerLinkActive="is-active"
        [routerLinkActiveOptions]="{ exact: true }"
        >Create Note</a
      >
    </li>
    <li>
      <button (click)="handleLogout()">Logout</button>
    </li>

    }@else {

    <!-- ?Guest Links -->

    <li>
      <a
        routerLink="/login"
        routerLinkActive="is-active"
        [routerLinkActiveOptions]="{ exact: true }"
        >Login</a
      >
    </li>
    <li>
      <a
        routerLink="/signup"
        routerLinkActive="is-active"
        [routerLinkActiveOptions]="{ exact: true }"
        >Sign Up</a
      >
    </li>

    }
  </ul>
</nav>

// front-end/src/components/navigation/Navigation.tsx
// src/components/navigation/Navigation.tsx
import { NavLink, useNavigate } from "react-router-dom";
import { useAuth } from "../../contexts/useAuth";
import { useAuthService } from "../../services/authService";

const Navigation: React.FC = () => {
	const { loggedIn, logout } = useAuth();
	const navigate = useNavigate();
	const { logoutUser } = useAuthService();

	const handleLogout = () => {
		logout();
		try {
			logoutUser();
			navigate("/login");
		} catch (error) {
			console.log(error);
		}
	};

	const linkClassNames = ({ isActive }: { isActive: boolean }) =>
		`text-white px-4 py-2 rounded-md text-sm font-medium ${
			isActive ? "bg-gray-900" : "hover:bg-gray-700"
		}`;

	return (
		<nav className="bg-gray-800 p-2">
			<ul className="flex items-center justify-start space-x-4">
				<li className="self-start">
					<NavLink to="/">
						<img
							src="/logo-white-notitle.png"
							alt="Logo"
							className="h-10"
						/>
					</NavLink>
				</li>
				{loggedIn ? (
					<>
						<li>
							<NavLink
								to="/notes"
								className={linkClassNames}
							>
								Notes
							</NavLink>
						</li>
						<li>
							<NavLink
								to="/create-note"
								className={linkClassNames}
							>
								Create Note
							</NavLink>
						</li>
						<li>
							<button
								onClick={handleLogout}
								className="text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-700"
							>
								Logout
							</button>
						</li>
					</>
				) : (
					<>
						<li>
							<NavLink
								to="/login"
								className={linkClassNames}
							>
								Login
							</NavLink>
						</li>
						<li>
							<NavLink
								to="/signup"
								className={linkClassNames}
							>
								Sign Up
							</NavLink>
						</li>
					</>
				)}
			</ul>
		</nav>
	);
};

export default Navigation;
