// front-end/src/components/notes/NoteDetail.tsx
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { deleteNote, getNote, updateNote } from "../../services/noteService";
import { TNote } from "../../types/note";
import { FaPen, FaTrashAlt } from "react-icons/fa";
import Loader from "../common/Loader/Loader";

const NoteDetail: React.FC = () => {
	const { id } = useParams<{ id: string }>();
	const [note, setNote] = useState<TNote>();
	const [isEditing, setIsEditing] = useState(false);
	const [editedText, setEditedText] = useState("");
	const token = localStorage.getItem("authToken");
	const navigate = useNavigate();

	useEffect(() => {
		const fetchNote = async () => {
			if (token) {
				const data = await getNote(id as string, token);
				setNote(data);
				setEditedText(data.text);
			}
		};

		fetchNote();
	}, [id, token]);

	const handleRemoveClick = async () => {
		try {
			const response = await deleteNote(id as string, token as string);
			if (response === 204) {
				alert("Note deleted successfully");
				navigate("/notes");
			}
		} catch (error) {
			alert("Failed to delete note");
		}
	};

	const handleEditClick = () => {
		setIsEditing(true);
	};

	const handleInputChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
		setEditedText(e.target.value);
	};

	const handleKeyDown = async (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
		if (e.key === "Enter") {
			try {
				if (note) {
					const updatedNote = { ...note, text: editedText };
					await updateNote(id as string, updatedNote, token as string);
					setNote(updatedNote);
					setIsEditing(false);
				}
			} catch (error) {
				alert("Failed to update note");
			}
		} else if (e.key === "Escape") {
			setIsEditing(false);
			setEditedText(note?.text ?? "");
		}
	};

	if (!note) {
		return <Loader />;
	}

	return (
		<div className="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow-lg mt-8 relative">
			<h2 className="text-3xl font-extrabold mb-1 text-blue-900">
				{note.title}
			</h2>
			<p className="text-gray-500 mt-1 text-sm mb-4">
				{new Date(note.createdAt).toLocaleString()}
			</p>
			<div className="text-gray-700 text-lg break-words whitespace-pre-wrap p-4 border border-gray-200 rounded-lg">
				{isEditing ? (
					<textarea
						value={editedText}
						onChange={handleInputChange}
						onKeyDown={handleKeyDown}
						className="w-full border border-gray-300 rounded-lg p-2"
					/>
				) : (
					<p>{note.text}</p>
				)}
			</div>
			{isEditing && (
				<div className="mt-2 text-gray-500 text-sm">
					Press Enter to save or Esc to discard changes
				</div>
			)}
			<div className="mt-6 flex justify-between items-center">
				<button
					className="bg-blue-900 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-all"
					onClick={() => navigate("/notes")}
				>
					Back to Notes
				</button>
				<div className="flex gap-3">
					<FaPen
						className="text-gray-400 hover:text-gray-700 cursor-pointer transition-all"
						onClick={handleEditClick}
					/>
					<FaTrashAlt
						className="text-gray-400 hover:text-gray-700 cursor-pointer transition-all"
						onClick={handleRemoveClick}
					/>
				</div>
			</div>
		</div>
	);
};

export default NoteDetail;

// front-end-angular/src/app/components/notes/note-detail/note-detail.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  OnDestroy,
  OnInit,
  WritableSignal,
  signal,
} from '@angular/core';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { TNote } from '../../../types/note';
import { NoteService } from '../../../services/note.service';
import { Subject, take, takeUntil } from 'rxjs';
import { FormsModule } from '@angular/forms';
import { faPen, faTrash } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

@Component({
  selector: 'app-note-detail',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, FontAwesomeModule],
  templateUrl: './note-detail.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NoteDetailComponent implements OnInit, OnDestroy {
  id!: string;
  destroy$: Subject<void> = new Subject<void>();
  note: WritableSignal<TNote | null> = signal<TNote | null>(null);
  isEditing: WritableSignal<boolean> = signal<boolean>(false);
  penIcon = faPen;
  trashIcon = faTrash;
  editedNote: string = '';
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private noteService: NoteService
  ) {}
  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.id = id;
      this.getNote(id);
    } else {
      this.router.navigate(['/notes']);
      return;
    }
  }
  private getNote(noteId: string) {
    this.noteService
      .getNote(noteId)
      .pipe(takeUntil(this.destroy$))
      .subscribe((n) => {
        this.note.set(n);
        this.editedNote = n.text;
      });
  }

  handleEditClick() {
    this.isEditing.set(!this.isEditing());
  }

  handleKeyDown($event: KeyboardEvent) {
    const noteBeforeUpdate = this.note();
    if (noteBeforeUpdate) {
      if ($event.key === 'Enter') {
        $event.preventDefault();
        this.isEditing.set(false);
        this.noteService
          .updateNote(this.id, {
            title: noteBeforeUpdate.title,
            text: this.editedNote,
          })
          .pipe(take(1))
          .subscribe((n) => this.note.set(n));
      } else if ($event.key === 'Escape') {
        this.isEditing.set(false);
        this.note.set(noteBeforeUpdate);
      }
    }
  }
  handleRemoveClick(noteId: string | undefined) {
    if (noteId) {
      this.noteService
        .deleteNote(noteId)
        .pipe(take(1))
        .subscribe(() => this.router.navigate(['/notes']));
    }
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow-lg mt-8 relative">
  <h2 class="text-3xl font-extrabold mb-1 text-blue-900">
    {{ note()?.title }}
  </h2>
  <p class="text-gray-500 mt-1 text-sm mb-4">
    {{ note()?.createdAt | date : "short" }}
  </p>
  <div class="">
    @if(isEditing()){

    <textarea
      [(ngModel)]="editedNote"
      name="edit"
      (keydown)="handleKeyDown($event)"
      class="text-gray-700 text-lg break-words whitespace-pre-wrap p-4 border w-full"
    ></textarea>

    }@else{
    <p class="text-gray-700 text-lg break-words whitespace-pre-wrap p-4 border">
      {{ note()?.text }}
    </p>

    }
  </div>
  @if (isEditing()) {
  <div class="mt-2 text-gray-500 text-sm">
    Press Enter to save or Esc to discard changes
  </div>
  }
  <div class="mt-6 flex justify-between items-center">
    <a
      class="bg-blue-900 text-white px-4 py-2 rounded-lg hover:bg-blue-700 hover:scale-105 transition-all"
      routerLink="/notes"
    >
      Back to Notes
    </a>
    <div class="flex gap-3">
      <fa-icon
        [icon]="penIcon"
        class="text-gray-400 hover:text-gray-700 cursor-pointer transition-all"
        (click)="handleEditClick()"
      />
      <fa-icon
        [icon]="trashIcon"
        class="text-gray-400 hover:text-gray-700 cursor-pointer transition-all"
        (click)="handleRemoveClick(note()?._id)"
      />
    </div>
  </div>
</div>
